"""XMPP 内置适配器共享常量。"""

XMPP_GATEWAY_NAME = "xmpp_gateway"
SUPPORTED_CONFIG_VERSION = "0.1.5"
DEFAULT_XMPP_HOST = "127.0.0.1"
DEFAULT_XMPP_PORT = 5222
DEFAULT_RECONNECT_DELAY_SEC = 5.0
DEFAULT_HEARTBEAT_INTERVAL_SEC = 0.0
DEFAULT_ACTION_TIMEOUT_SEC = 15.0
DEFAULT_CHAT_LIST_TYPE = "whitelist"
